language: node_js
cache:
  - node_modules
node_js:
  - '0.11'
  - '0.10'
after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
