'use strict';

exports.compact    = require('./compact');
exports.compose    = require('./compose');
exports.curry      = require('./curry');
exports.detect     = require('./detect');
exports.divmod     = require('./divmod');
exports.drop       = require('./drop');
exports.filter     = require('./filter');
exports.first      = require('./first');
exports.flatten    = require('./flatten');
exports.get        = require('./get');
exports.index      = require('./index');
exports.isBoolean  = require('./isBoolean');
exports.isFunction = require('./isFunction');
exports.isNumber   = require('./isNumber');
exports.isObject   = require('./isObject');
exports.last       = require('./last');
exports.map        = require('./map');
exports.pick       = require('./pick');
exports.range      = require('./range');
exports.reduce     = require('./reduce');
exports.reject     = require('./reject');
exports.take       = require('./take');
exports.zip        = require('./zip');
